/* eslint @typescript-eslint/no-explicit-any: off, react-hooks/preserve-manual-memoization: off, react-hooks/purity: off */
"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { CrmPanel,ExpensesPanel,ClockPanel,AdminPanel } from "./panels";
type Member={id:string;name:string;color:string};type Event={id:string;memberId:string;title:string;date:string;start:string;end:string;kind:string};
const TEAM:Member[]=[{id:"pranav",name:"Pranav",color:"#4f83f1"},{id:"golam",name:"Golam",color:"#315fda"},{id:"kerem",name:"Kerem",color:"#71a2f7"},{id:"hammaad",name:"Hammaad",color:"#47a9bd"}];
const DAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const pad=(n:number)=>String(n).padStart(2,"0");
const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const localMonday=(base:Date,offset:number)=>{const d=new Date(base.getFullYear(),base.getMonth(),base.getDate());d.setDate(d.getDate()-((d.getDay()+6)%7)+offset*7);return d};
export default function Desk(){
 const [member,setMember]=useState<Member|null>(null),[pin,setPin]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[events,setEvents]=useState<Event[]>([]),[workspace,setWorkspace]=useState<any>({contacts:[],expenses:[],shifts:[],members:TEAM}),[view,setView]=useState("Schedule"),[offset,setOffset]=useState(0),[selected,setSelected]=useState(TEAM.map(x=>x.id)),[mode,setMode]=useState("Week"),[modal,setModal]=useState(false),[busy,setBusy]=useState(false);
 const week=useMemo(()=>localMonday(new Date(),offset),[offset]),days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(week);d.setDate(d.getDate()+i);return d}),[week]);
 const loadEvents=useCallback(async()=>{const [r,w]=await Promise.all([fetch("/api/events",{cache:"no-store"}),fetch("/api/workspace",{cache:"no-store"})]);if(r.ok){const d:any=await r.json();setEvents(d.events||[])}else if(r.status===401)setMember(null);if(w.ok)setWorkspace(await w.json() as any)},[]);
 useEffect(()=>{fetch("/api/login",{cache:"no-store"}).then(r=>r.json()).then(async (d:any)=>{setMember(d.member||null);if(d.member)await loadEvents()}).catch(()=>setError("Couldn’t connect to the intern desk.")).finally(()=>setLoading(false))},[loadEvents]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setBusy(true);try{const r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({memberId:(new FormData(e.currentTarget).get("member")||""),pin})});const d:any=await r.json();if(!r.ok)throw Error(d.error||"Sign-in didn’t work.");setMember(d.member);setPin("");await loadEvents()}catch(x:any){setError(x.message)}finally{setBusy(false)}}
 async function logout(){await fetch("/api/logout",{method:"POST"});setMember(null);setEvents([]);setWorkspace({contacts:[],expenses:[],shifts:[],members:TEAM})}
 async function runAction(body:any){setError("");setBusy(true);try{const r=await fetch("/api/workspace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d:any=await r.json();if(!r.ok)throw Error(d.error||"Couldn’t save that change.");await loadEvents()}catch(x:any){setError(x.message)}finally{setBusy(false)}}
 async function createEvent(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),body=Object.fromEntries(f);setBusy(true);try{const r=await fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d:any=await r.json();if(!r.ok)throw Error(d.error);setModal(false);await loadEvents()}catch(x:any){setError(x.message)}finally{setBusy(false)}}
 const today=iso(new Date()),shown=events.filter(e=>selected.includes(e.memberId)&&e.date>=iso(days[0])&&e.date<=iso(days[6])&&(mode!=="Availability"||e.kind==="available"));
 if(loading)return <main className="login-screen"><p>Opening the intern desk…</p></main>;
 if(!member)return <main className="login-screen"><section className="login-card"><div className="fomo-mark">fomo</div><p className="kicker">GROWTH TEAM · INTERN DESK</p><h1>Welcome to the team desk</h1><p>Sign in with your ChatGPT account to view the shared schedule.</p><form onSubmit={login}><label>Your name<select name="member" defaultValue="golam">{TEAM.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Six-digit PIN<input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" autoComplete="one-time-code" placeholder="••••••" /></label>{error&&<p className="error">{error}</p>}<button disabled={busy||pin.length!==6} className="primary-button">{busy?"Checking…":"Open intern desk"}</button><small>Team PINs are private. Don’t share them in a message.</small></form></section></main>;
 return <main className="desk-shell"><aside className="sidebar"><Link className="sidebar-brand" href="/">fomo<span>intern desk</span></Link><p className="sidebar-label">TEAM WORKSPACE</p><nav className="side-nav">{["Schedule","Time clock","Reimbursements","CRM",...(member.id==="golam"?["Admin portal"]:[])].map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}><i>{({"Schedule":"▦","Time clock":"◷","Reimbursements":"↗","CRM":"◎","Admin portal":"⚙"} as any)[v]}</i>{v}</button>)}</nav><div className="sidebar-account"><span className="account-avatar" style={{"--member-color":member.color} as React.CSSProperties}>{member.name[0]}</span><div><b>{member.name}</b><small>Growth intern</small></div><button onClick={logout}>Sign out</button></div></aside><div className="desk-main"><header className="topbar"><span className="breadcrumb">fomo / <b>{view}</b></span><div className="topbar-right"><time>{new Date().toLocaleString("en-US",{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time><span className="topbar-user">{member.name}</span></div></header>
 {view==="Schedule"&&<>
 <div className="page-heading"><div><p className="kicker">TEAM WORKSPACE</p><h1>Schedule</h1><p>See the team’s week, add your work blocks, and plan around class times.</p></div><span className="timezone-chip">New York time</span></div><div className="schedule-layout"><aside className="intern-panel"><h3>INTERNS</h3>{TEAM.map(m=><label className="intern-option" key={m.id}><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(e.target.checked?[...selected,m.id]:selected.filter(x=>x!==m.id))} style={{accentColor:m.color}}/><span>{m.name}{m.id===member.id?" (you)":""}<small>Growth intern</small></span></label>)}<button className="outline" onClick={()=>setSelected(selected.length===TEAM.length?[]:TEAM.map(m=>m.id))}>{selected.length===TEAM.length?"Show selected":"Show everyone"}</button><p>Choose who appears on the calendar. Click a block for its details. Classes are shown by time only.</p></aside>
 <section className="calendar-panel"><div className="calendar-toolbar"><div className="date-controls"><button onClick={()=>setOffset(offset-1)} aria-label="Previous week">‹</button><button onClick={()=>setOffset(offset+1)} aria-label="Next week">›</button><button className="today-button" onClick={()=>setOffset(0)}>Today</button><h2>{days[0].toLocaleDateString("en-US",{month:"short",day:"numeric"})} – {days[6].toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}</h2></div><div className="calendar-actions"><div className="toggle"><button className={mode==="Week"?"selected":""} onClick={()=>setMode("Week")}>Week</button><button className={mode==="Availability"?"selected":""} onClick={()=>setMode("Availability")}>Availability</button></div><button className="add-button" onClick={()=>setModal(true)}>＋ Add to schedule</button></div></div>
 <div className="calendar-scroll"><div className="week-head"><div></div>{days.map((d,i)=><div key={i} className={iso(d)===today?"is-today":""}><small>{DAYS[i]}</small><strong>{d.getDate()}</strong><span className="color-ticks">{TEAM.map(m=><i key={m.id} style={{background:m.color}}/>)}</span><span className="initial-ticks">{TEAM.map(m=><i key={m.id}>{m.name[0]}</i>)}</span></div>)}</div>
 <div className="week-grid"><div className="time-col">{Array.from({length:17},(_,i)=><span key={i}>{i===0?"7 AM":i<5?`${i+7} AM`:i===5?"12 PM":i<12?`${i-5} PM`:i===12?"7 PM":`${i-5} PM`}</span>)}</div>{days.map(d=><div className="day-lane" key={iso(d)}>{shown.filter(e=>e.date===iso(d)).map(e=>{const m=TEAM.find(x=>x.id===e.memberId)!,start=e.start.split(":").map(Number),end=e.end.split(":").map(Number),top=((start[0]*60+start[1]-420)/1020)*100,height=((end[0]*60+end[1]-start[0]*60-start[1])/1020)*100;return <button key={e.id} className="event-block" style={{top:`${top}%`,height:`${Math.max(2,height)}%`,"--member-color":m.color} as React.CSSProperties} title={`${m.name}: ${e.title}, ${e.start}–${e.end}`}><strong>{e.title}</strong><small>{e.start}–{e.end}</small><i>{m.name[0]}</i></button>})}</div>)}</div></div>
 <div className="calendar-foot"><span><i className="legend-class"/> Class</span><span><i className="legend-other"/> Team schedule</span><span>All times shown in New York time</span></div></section></div></>}
 {view==="Admin portal"&&member.id==="golam"&&<AdminPanel/>}
 {view==="CRM"&&<CrmPanel rows={workspace.contacts} members={workspace.members} me={member} run={runAction} busy={busy}/>}
 {view==="Reimbursements"&&<ExpensesPanel rows={workspace.expenses} members={workspace.members} me={member} run={runAction} busy={busy}/>}
 {view==="Time clock"&&<ClockPanel rows={workspace.shifts} members={workspace.members} me={member} run={runAction} busy={busy}/>}
 {error&&<div role="status" className="toast" onClick={()=>setError("")}>{error}<button aria-label="Dismiss">×</button></div>}
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(false)}><form className="event-modal" onSubmit={createEvent} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>Add to schedule</h2><button type="button" onClick={()=>setModal(false)}>×</button></div><label>Date<input required type="date" name="date" defaultValue={today}/></label><div className="form-row"><label>Start<input required type="time" name="start" defaultValue="09:00"/></label><label>End<input required type="time" name="end" defaultValue="10:00"/></label></div><label>Type<select name="kind"><option>Work</option><option>Busy</option><option>Available</option></select></label><p>Only you can edit this block. Other interns see the time as “Busy.”</p><button className="primary-button" disabled={busy}>Save to team schedule</button></form></div>}
 </div></main>;
}
